### ISSUE TITLE
NullPointerException when search a series with a title that not exist

### ISSUE THREAD

**Issue by fmunozse** [Omertron/api-thetvdb#17]
Hi

Just to inform when is searching a series that not exist, api throw a null pointer exception.

`String title = "fargo xsadasdasaad";`
`String language = "eng";	`
`List<Series> results = tvDB.searchSeries(title, language);
`

See logs:
 2016-03-13 21:51:13.296 ERROR 32142 --- [nio-8080-exec-2] c.j.aop.logging.LoggingAspect            : Exception in com.jtrackseries.service.TVDBScratchService.findByTitle() with cause = null and exception {}

java.lang.NullPointerException: null
	at com.omertron.thetvdbapi.tools.DOMHelper.getEventDocFromUrl(DOMHelper.java:122) ~[thetvdbapi-1.8.jar:]
	at com.omertron.thetvdbapi.tools.TvdbParser.getSeriesList(TvdbParser.java:256) ~[thetvdbapi-1.8.jar:]
	at com.omertron.thetvdbapi.TheTVDBApi.searchSeries(TheTVDBApi.java:362) ~[thetvdbapi-1.8.jar:]
	at com.jtrackseries.service.TVDBScratchService.findByTitle(TVDBScratchService.java:31) ~[classes/:na]

**Comment by Omertron** [comment]
v1.9 released
